name: edgex-device-snmp
base: core20 
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh, geneva, hanoi
# 2: ireland, jakarta
epoch: 2

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-snmp]

apps:
  device-snmp:
    adapter: full
    command: bin/device-snmp -confdir $SNAP_DATA/config/device-snmp -profile res --registry $CONSUL_ADDR
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
      DEVICE_PROFILESDIR: $SNAP_DATA/config/device-snmp/res/profiles
      DEVICE_DEVICESDIR: $SNAP_DATA/config/device-snmp/res/devices
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-snmp/secrets-token.json
      WRITABLE_LOGLEVEL: 'INFO'
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-snmp

parts:
  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps: [go/1.18/stable]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure $SNAPCRAFT_PART_INSTALL/snap/hooks/configure
      install -DT ./cmd/install/install $SNAPCRAFT_PART_INSTALL/snap/hooks/install

  device-snmp:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    stage-packages: [libzmq5]
    build-snaps:
      - go/1.18/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      go mod tidy
      make build

      install -DT "./cmd/device-snmp" "$SNAPCRAFT_PART_INSTALL/bin/device-snmp"

      # copy all config files
      mkdir -p $SNAPCRAFT_PART_INSTALL/config/device-snmp/res
      cp -rv cmd/res/configuration.toml $SNAPCRAFT_PART_INSTALL/config/device-snmp/res/configuration.toml 
      cp -rv cmd/res/devices $SNAPCRAFT_PART_INSTALL/config/device-snmp/res/devices     
      cp -rv cmd/res/profiles $SNAPCRAFT_PART_INSTALL/config/device-snmp/res/profiles      

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-snmp/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-snmp/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-snmp.metainfo.xml] 